version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      - MONGODB_URI=il_tuo_mongodb_uri
      - JWT_SECRET=il_tuo_secret_key

  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - backend